### ISSUE TITLE
`DefaultLeaderElector::elect_leader` binary search

### ISSUE THREAD

**Issue by matteojug** [distributed-lab/bpcon#16]
In `DefaultLeaderElector::elect_leader`, the `binary_search_by` is not really helping since we are constructing the `cumulative_weights` array each time: either we build it once (and then use the bin search, but note that there are other places where we still do a linear scan of the weights), or we can just find the matching index in the for loop above (~`leader.rs:139`).

**Comment by nikitamasych** [comment]
Yep, thank you. I modified election to deduce party index on the go of prefix sums; won't do caching of `cumulative_weights` since design of the `LeaderElector` shall not care about `Party`'s state.
